# Generated by Django 4.0.6 on 2024-06-02 09:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=datetime.datetime(2024, 6, 2, 9, 20, 17, 612151, tzinfo=utc), upload_to='intruder_image/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
